<?php

return [
    'free' => [
        'name' => 'Free',
        'amount' => 0,
        'features' => [
            'users',
            'routes',
            'pireps',
        ],
        'display_group' => 'Free',
        'display_features' => [
            'Unlimited users',
            'Unlimited routes',
            'Unlimited PIREPS',
        ],
    ],
    'cadet_monthly' => [
        'name' => 'Cadet Monthly',
        'amount' => 5,
        'interval' => 'monthly',
        'features' => [
            'users',
            'routes',
            'pireps',
            'leaderboard',
            'events',
            'logo',
            'custom-fields',
        ],
        'display_group' => 'Cadet',
        'display_features' => [
            'Everything in Free',
            'Events management',
            'Custom logo branding',
            'Leaderboard system',
            'Custom fields',
        ],
    ],
    'cadet_yearly' => [
        'name' => 'Cadet Yearly',
        'amount' => 50,
        'interval' => 'yearly',
        'features' => [
            'users',
            'routes',
            'pireps',
            'leaderboard',
            'events',
            'logo',
            'custom-fields',
        ],
        'display_group' => 'Cadet',
        'display_features' => [
            'Everything in Free',
            'Events management',
            'Custom logo branding',
            'Leaderboard system',
            'Custom fields',
        ],
    ],
    'captain_monthly' => [
        'name' => 'Captain Monthly',
        'amount' => 10,
        'interval' => 'monthly',
        'features' => [
            'users',
            'routes',
            'pireps',
            'leaderboard',
            'events',
            'logo',
            'custom-fields',
            'discord-integration',
        ],
        'display_group' => 'Captain',
        'display_features' => [
            'Everything in Cadet',
            'Discord integration',
            'Priority support',
        ],
    ],
    'captain_yearly' => [
        'name' => 'Captain Yearly',
        'amount' => 100,
        'interval' => 'yearly',
        'features' => [
            'users',
            'routes',
            'pireps',
            'leaderboard',
            'events',
            'logo',
            'custom-fields',
            'discord-integration',
        ],
        'display_group' => 'Captain',
        'display_features' => [
            'Everything in Cadet',
            'Discord integration',
            'Priority support',
        ],
    ],
];